[project]
name = "asteroids"
version = "0.1.0"
description = "Asteroids game developed in python as coding exercise of Boot.dev's python challenge course by Caroline Sampaio."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame==2.6.1",
]
